job_market_bq:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      dataset: "{{ env_var('BQ_MARTS_DATASET') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_KEYFILE_PATH') }}"
      location: "{{ env_var('GCP_REGION') }}"
      priority: interactive
