job_market_bq:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GOOGLE_CLOUD_PROJECT') }}"
      dataset: "{{ env_var('BQ_MARTS_DATASET') }}"
      threads: 8
      location: "{{ env_var('GCP_REGION') }}"
      priority: interactive


